def commonLibraries = rootProject.ext.has("companionCommonLibraries")
        ? rootProject.ext.companionCommonLibraries
        : []
def bundledLibraries = rootProject.ext.has("companionBundledLibraries")
        ? rootProject.ext.companionBundledLibraries
        : []

architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    // We depend on Fabric Loader here to use the Fabric @Environment annotations,
    // which get remapped to the correct annotations on each platform.
    // Do NOT use other classes from Fabric Loader.
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "io.github.tritium_launcher:tritium-mod-api:0.1.2"
    modCompileOnly "dev.latvian.mods:kubejs-neoforge:2101.7.2-build.365"

    (commonLibraries + bundledLibraries).each { dep ->
        implementation dep
    }
}
