modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Tritium-Launcher/Tritium-Companion"
license = "MIT"

[[mods]]
modId = "tritiumcompanion"
version = "${version}"
displayName = "Tritium Companion"
authors = "FooterManDev"
description = '''
Provides utilities for Tritium, including network operations and registry dumping.
'''
logoFile = "icon.png"

[[dependencies.tritiumcompanion]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tritiumcompanion]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "tritiumcompanion.mixins.json"
